import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <div style={{position:"relative",height:"100vh",width:"100vw"}}>
    
    
    <div className={styles.mymain}>
<Image src="/bardo.png" alt="bardock" 
 layout="fill"
 objectPosition="center"
className={styles.myimg}
/>
</div>

<div className={styles.mymain}> </div>


 <div style={{ position: 'relative', zIndex: 1 ,color:"wheat" }}>
 
  <div style={{position:"relative", top:"0",height:"10vh",zIndex:+1,
      backgroundColor:"transparent",color:"white",
      display:"flex",flexDirection:"row",alignContent:"center",justifyContent:"center",alignItems:"center",
      gap:"20px",fontSize:"25px",boxShadow:"0 0 4px rgba(255, 255, 255, 0.297)"
    }}>
     <div>Hi</div>
     <div>To</div>
     <div>Web</div>
  </div> 

  <div style={{height:"90vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}>{children}</div>

   </div>


</div>
      </body>
    </html>
  )
}
